### ISSUE TITLE
Psc scan running forever in windows

### ISSUE THREAD

**Issue by shoebham** [anishathalye/periscope#10]
Hi, I followed the steps given [here](https://github.com/anishathalye/periscope/issues/2#issuecomment-672163129) to build periscope on windows, but when i run ```psc scan``` it runs indefinitely even for one file.
![image](https://user-images.githubusercontent.com/25881429/209928434-1ec3c700-c2cc-4634-87c7-cca10c4c05ed.png)

Is there something wrong with the code, or is it my machine.

**Comment by shoebham** [comment]
Update: I tried installing different versions at different commits and found out that the problem arose after [this](https://github.com/anishathalye/periscope/commit/1f1e65f7f6de0e4fa982cdd28fe3cb5775de1a48) commit, I installed the commit just before it and it runs just fine.

**Comment by anishathalye** [comment]
Thanks, that is helpful.

One particular issue is that commit introduced [this function](https://github.com/anishathalye/periscope/blob/e40c2c72f480e23b33d971185f007ad2e56867a8/internal/db/db.go#L261) that is assuming UNIX-style directory paths, where root is "/", whereas on Windows it's going to be something like "C:\", and so that's an infinite loop.

Periscope is not tested on Windows. Given that it interacts with the filesystem and uses some slightly fancy features of the filesystem (special treatment of symlinks, special treatment of hard links), I'd be more comfortable with people using it on Windows after we get the test suite running there. I would love to get everything working on Windows (and it's likely a small fix), but I don't currently have the bandwidth to work on it, so I can't estimate when that will be done, unless someone submits a PR.

**Comment by anishathalye** [comment]
Closing in favor of https://github.com/anishathalye/periscope/issues/1, which I've updated to include this issue.
